#!/bin/bash

#Transfer my website log files into VirtualBox.

cd ~/Downloads
rm access.log
wget "http://www.templeos.org/Tmp/access.log"
~/TAD/Bin/VirtualBox/vb_mnt
mkdir /mnt/vb_disk/Tmp
mkdir /mnt/vb_disk/Tmp/Logs
mv ~/Downloads/a*.log /mnt/vb_disk/Tmp/Logs
~/TAD/Bin/VirtualBox/vb_umnt

