#!/bin/bash

#Transfer my /Home files out of VirtualBox.

~/TAD/Bin/VirtualBox/vb_mnt
rm -R ~/TOS/Site1/Wb
rm -R ~/TOS/Home
mv /mnt/vb_disk/Wb/TempleOSStaff.ISO ~/TOS
cp -R --preserve=all /mnt/vb_disk/Wb ~/TOS/Site1/Wb
cp --preserve=all /mnt/vb_disk/Wb/Home/Web/index.html ~/TOS/Site1
cp --preserve=all /mnt/vb_disk/Wb/Home/Web/TempleOS.html ~/TOS/Site1
cp -R --preserve=all /mnt/vb_disk/Home ~/TOS
chmod -R 777 ~/TOS
~/TAD/Bin/VirtualBox/vb_umnt

