+] Adam
  +] SysMsgFlags
      sys_msg_flags[0]=0x53;
      +] SysRegVer
      registry_version=2.030;
      +] TempleOS
  +] DiningStars
      F64 best_score=9999.0000;
      +] EagleDive
      I64 best_score=2;
      +] BlackDiamond
      I64 best_score=35;
      +] CastleFrankenstein
      F64 best_score=9999.0000;
      +] ZoneOut
      F64 best_score=95.3249;
      +] Varoom
      F64 best_score=11.8623;
      +] BugBird
      F64 best_score=9999.0000;
      +] TimeOut
      I64 best_score=0;
      +] RawHide
      F64 best_score=9999.0000;
      +] KeepAway
      I64 best_score0=0,best_score1=9999;
      +] XCaliber
      I64 best_score=70;
    I64 msg_flags=1;
      +] Wenceslas
      F64 best_score=9999.0000;
      +] BulgeBomber
      I64 best_score=45;
      