+] Adam
  +] TempleOS
      +] SysMsgFlags
          sys_msg_flags[0]=0;
          +] SysRegVer
          registry_version=1.060;
            +] TempleOS
  +] Varoom
      F64 best_score=9999.0000;
      +] BugBird
      F64 best_score=9999.0000;
      +] TimeOut
      I64 best_score=0;
      +] RawHide
      F64 best_score=9999.0000;
      +] KeepAway
      I64 best_score0=0,best_score1=9999;
      +] XCaliber
      I64 best_score=0;
      +] Wenceslas
      F64 best_score=9999.0000;
      +] BulgeBomber
      I64 best_score=99999;
      +] EagleDive
      I64 best_score=0;
      +] CastleFrankenstein
      F64 best_score=69.1680;
      +] ZoneOut
      F64 best_score=76.8861;
      