+] Adam
  +] TempleOS
      +] SysMsgFlags
          sys_msg_flags[0]=0x205;
          +] SysRegVer
          registry_version=1.010;
            +] DemoCompany
  +] Game1
      F64 best_score=1.23;
    +] SimpleVal
          1234;
            +] TempleOS
  +] EagleDive
      I64 best_score=5;
      +] FPS
      F64 best_score=55.2079;
      +] ZoneOut
      F64 best_score=9999.0000;
      +] BirdLand
      F64 best_score=16.1659;
      +] Timeout
      I64 best_score=14797;
      +] RawHide
      F64 best_score=9999.0000;
      +] KeepAway
      I64 best_score0=0,best_score1=9999;
      +] XCaliber
      I64 best_score=118;
      +] Wenceslas
      F64 best_score=9999.0000;
      +] Bomber
      I64 best_score=99999;
      