+] Adam
  +] TempleOS
      +] SysMsgFlags
          sys_msg_flags[0]=0;
          +] SysRegVer
          registry_version=1.060;
            +] SysMsgFlags
      sys_msg_flags[0]=0x59;
      +] SysRegVer
      registry_version=1.100;
      +] TempleOS
  +] DiningStars
      F64 best_score=9999.0000;
      +] EagleDive
      I64 best_score=1;
      +] CastleFrankenstein
      F64 best_score=51.6260;
      +] ZoneOut
      F64 best_score=76.8861;
      +] Varoom
      F64 best_score=38.1517;
      +] BugBird
      F64 best_score=17.7538;
      +] TimeOut
      I64 best_score=11012;
      +] RawHide
      F64 best_score=9999.0000;
      +] KeepAway
      I64 best_score0=28,best_score1=10;
      +] XCaliber
      I64 best_score=32;
      +] Wenceslas
      F64 best_score=99.4480;
      +] BulgeBomber
      I64 best_score=37;
      