#!/bin/bash

#Transfer BMP screenshot movie files out of VMware.

echo VMware Mov
~/TOS/Bin/VMware/vm_mnt
rm -R ~/Tmp/Mov
mkdir ~/Tmp/Mov
cp -R --preserve=all /mnt/vm_disk/Tmp/ScrnShots ~/Tmp/Mov/ScrnShots
for f in ~/Tmp/Mov/ScrnShots/*.Z; do ~/TOS/Bin/TOSZ $f; done
chmod -R 777 ~/Tmp/Mov/ScrnShots
cp -R --preserve=all /mnt/vm_disk/Tmp/*.SND ~/Tmp/Mov
chmod -R 777 ~/Tmp
~/TOS/Bin/VMware/vm_umnt

