#!/bin/bash

#Extract .SND from VMware.  Then, mix .SND and .FLV to make .FLV.

echo Mix flv
~/TAD/Bin/VMware/vm_mnt
mv ~/Tmp/Movie.flv ~/Tmp/OldMovie.flv
cp --preserve=timestamps /mnt/vm_disk/Temp/*.SND ~/Tmp
chmod -R 777 ~/Tmp
~/TAD/Bin/VMware/vm_umnt
cd ~/Tmp
ffmpeg -i Video.flv -i Audio000.SND -filter_complex amix=inputs=2:duration=first Movie.flv
mv Video.flv OldVideo.flv
mv Audio000.SND OldAudio.SND


