#!/bin/bash

#Transfer my website log files into QEMU.

cd ~/Downloads
rm access.log
wget "http://www.templeos.org/Tmp/access.log"
~/TAD/Bin/emu_mnt
mkdir /mnt/qemu_disk/Tmp
mkdir /mnt/qemu_disk/Tmp/Logs
mv ~/Downloads/a*.log /mnt/qemu_disk/Tmp/Logs
~/TAD/Bin/emu_umnt

