#!/bin/bash

#Start QEMU and boot Dropbox CDROM in order to install new TempleOS files.

qemu-system-x86_64 -hda ~/qemu_disk.qcow2 -machine kernel_irqchip=off -smp cores=24 -enable-kvm -cpu host -m 4096 -rtc base=localtime -soundhw pcspk -cdrom ~/Dropbox/Dianna/TempleOSStaff.ISO -boot d
