#!/bin/bash

#Transfer my /Home files into VirtualBox.

rm ~/TAD/Bin/*~
rm ~/TAD/Home/*~
rm ~/TAD/Home/Sup1/Sup1Bin/*~

cp -R --preserve=timestamps ~/TAD/Bin/God* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/IRCBots/TempleBot ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/emu* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/iso* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/make_* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/mix* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/vb* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/vm* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/TOSSocket* ~/TAD/Home/Sup1/Sup1CodeScraps/Comm

~/TAD/Bin/vb_mnt
rm -R /mnt/vb_disk/Home
cp -R --preserve=timestamps ~/TAD/Home /mnt/vb_disk
~/TAD/Bin/vb_umnt

