#!/bin/bash

#Transfer BMP screenshot movie files out of VirtualBox.

~/TAD/Bin/vb_mnt
rm -R ~/Tmp/Mov
mkdir ~/Tmp/Mov
cp -R --preserve=timestamps /mnt/vb_disk/Temp/ScreenShots ~/Tmp/Mov/ScreenShots
for f in ~/Tmp/Mov/ScreenShots/*.Z; do ~/TAD/Bin/TOSZ $f; done
chmod -R 777 ~/Tmp/Mov/ScreenShots
cp -R --preserve=timestamps /mnt/vb_disk/Temp/*.SND ~/Tmp/Mov
chmod -R 777 ~/Tmp
cd ~/Tmp/Mov/ScreenShots
ffmpeg -r 8 -i VID%05d.BMP -y Video.flv
ffmpeg -r 8 -i VID%05d.BMP -y Video.avi
cd ~/Tmp/Mov
ffmpeg -i Audio000.SND -ar 44100 Audio000.wav
ffmpeg -i Audio000.SND -ar 44100 Audio000.mp3
~/TAD/Bin/vb_umnt

