#!/bin/bash

#Transfer my /Home files out of VirtualBox.

~/TAD/Bin/vb_mnt
rm -R ~/TAD/Site1/Wb
rm -R ~/TAD/Home
mv /mnt/vb_disk/Wb/TempleOSStaff.ISO ~/TAD
cp -R --preserve=timestamps /mnt/vb_disk/Wb ~/TAD/Site1/Wb
cp --preserve=timestamps /mnt/vb_disk/Wb/Home/Web/index.html ~/TAD/Site1
cp --preserve=timestamps /mnt/vb_disk/Wb/Home/Web/index.html ~/TAD/Site1/TempleOS.html
cp -R --preserve=timestamps /mnt/vb_disk/Home ~/TAD
chmod -R 777 ~/TAD
~/TAD/Bin/vb_umnt
~/TAD/Bin/iso_mirror

