#!/bin/bash

#Transfer my /Home files out of VirtualBox.

~/TAD/Bin/vb_mnt
rm -R ~/TAD/www.templeos.org/Wb
rm -R ~/TAD/Home
mv /mnt/vb_disk/Wb/TempleOSStaff.ISO ~/Dropbox/Dianna
cp -R --preserve=timestamps /mnt/vb_disk/Wb ~/TAD/www.templeos.org/Wb
cp --preserve=timestamps /mnt/vb_disk/Wb/Home/Web/index.html ~/TAD/www.templeos.org
cp --preserve=timestamps /mnt/vb_disk/Wb/Home/Web/index.html ~/TAD/www.templeos.org/TempleOS.html
cp -R --preserve=timestamps /mnt/vb_disk/Home ~/TAD
chmod -R 777 ~/TAD
~/TAD/Bin/vb_umnt

