#!/bin/bash

#Transfer my /Home song files into VirtualBox.

~/TAD/Bin/vb_mnt
rm -R /mnt/vb_disk/Home/Sup1/Sup1Hymns
rm -R /mnt/vb_disk/Home/Sup1/Sup1Songs
cp -R --preserve=timestamps ~/TAD/Home/Sup1/Sup1Hymns /mnt/vb_disk/Home/Sup1
cp -R --preserve=timestamps ~/TAD/Home/Sup1/Sup1Songs /mnt/vb_disk/Home/Sup1
~/TAD/Bin/vb_umnt

