#!/bin/bash

#Transfer my /Home files into VMware.

rm ~/TAD/Bin/*~
rm ~/TAD/Home/*~
rm ~/TAD/Home/Sup1/Sup1Bin/*~
cp -R --preserve=timestamps ~/TAD/Bin/emu* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/vm* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/vb* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/mix* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/Bin/God* ~/TAD/Home/Sup1/Sup1Bin
cp -R --preserve=timestamps ~/TAD/IRCBots/TempleBot ~/TAD/Home/Sup1/Sup1Bin

echo VMware In
~/TAD/Bin/vm_mnt
rm -R /mnt/vm_disk/Home
cp -R --preserve=timestamps ~/TAD/Home /mnt/vm_disk
~/TAD/Bin/vm_umnt

