#!/bin/bash

#Transfer my website log files into VMware.

echo VMware Log
cd ~/Downloads
rm access.log
wget "http://www.templeos.org/Tmp/access.log"
~/TAD/Bin/vm_mnt
mkdir /mnt/vm_disk/Temp
mkdir /mnt/vm_disk/Temp/Logs
mv ~/Downloads/a*.log /mnt/vm_disk/Temp/Logs
~/TAD/Bin/vm_umnt

