#!/bin/bash

#Transfer my /Home files out of VMware.

echo VMware Out
~/TAD/Bin/vm_mnt
rm -R ~/TAD/www.templeos.org/Wb
rm -R ~/TAD/Home
mv /mnt/vm_disk/Wb/TempleOSStaff.ISO ~/Dropbox/Dianna
cp -R --preserve=timestamps /mnt/vm_disk/Wb ~/TAD/www.templeos.org/Wb
cp --preserve=timestamps /mnt/vm_disk/Wb/Home/Web/index.html ~/TAD/www.templeos.org
cp --preserve=timestamps /mnt/vm_disk/Wb/Home/Web/index.html ~/TAD/www.templeos.org/TempleOS.html
cp -R --preserve=timestamps /mnt/vm_disk/Home ~/TAD
chmod -R 777 ~/TAD
~/TAD/Bin/vm_umnt


