#!/bin/bash

#Transfer my /Home song files out of VMware.

~/TOS/Bin/VMware/vm_mnt
rm -R ~/TOS/Home/Sup1/Sup1Hymns
rm -R ~/TOS/Home/Sup1/Sup1Songs
cp -R --preserve=all /mnt/vm_disk/Home/Sup1/Sup1Hymns ~/TOS/Home/Sup1
chmod -R 777 ~/TOS
~/TOS/Bin/VMware/vm_umnt

