+] Adam
  +] LT
      +] SysMsgFlags
          sys_msg_flags[0]=0x2D8;
          +] SysRegVer
          registry_version=8.040;
            +] LT
  +] CircleTrace
      F64 best_score=999.0000;
      +] EagleDive
      I64 best_score=2;
      +] FPS
      F64 best_score=64.5574;
      +] ZoneOut
      F64 best_score=9999.0000;
      +] BirdLand
      F64 best_score=9999.0000;
      +] Timeout
      I64 best_score=0;
      +] RawHide
      F64 best_score=9999.0000;
      +] KeepAway
      I64 best_score0=0,best_score1=9999;
      +] Wenceslas
      F64 best_score=9999.0000;
      +] Bomber
      I64 best_score=99999;
      +] XCaliber
      I64 best_score=60;
      