#!/bin/bash

#Transfer BMP screenshot movie files out of QEMU.

~/TAD/Bin/QEMU/emu_mnt
rm -R ~/Tmp/Mov
mkdir ~/Tmp/Mov
cp -R --preserve=timestamps /mnt/qemu_disk/Tmp/ScrnShots ~/Tmp/Mov/ScrnShots
for f in ~/Tmp/Mov/ScrnShots/*.Z; do ~/TAD/Bin/TOSZ $f; done
chmod -R 777 ~/Tmp/Mov/ScrnShots
cp -R --preserve=timestamps /mnt/qemu_disk/Tmp/*.SND ~/Tmp/Mov
chmod -R 777 ~/Tmp
cd ~/Tmp/Mov/ScrnShots
ffmpeg -r 30 -i VID%05d.BMP -y Video.flv
ffmpeg -r 30 -i VID%05d.BMP -y Video.avi
cd ~/Tmp/Mov
ffmpeg -i Audio000.SND -ar 44100 Audio000.wav
ffmpeg -i Audio000.SND -ar 44100 Audio000.mp3
~/TAD/Bin/QEMU/emu_umnt

