#!/bin/bash

#Transfer /Home/ALM files out of QEMU.

~/TOS/Bin/QEMU/emu_mnt
rm -R ~/TOS/Site1ALM/Wb/Home/Web/ALM
rm -R ~/TOS/Home/ALM
cp -R --preserve=all /mnt/qemu_disk/Wb/Home/Web/ALM ~/TOS/Site1ALM/Wb/Home/Web/ALM
cp -R --preserve=all /mnt/qemu_disk/Home/ALM ~/TOS/Home/ALM
chmod -R 777 ~/TOS
~/TOS/Bin/QEMU/emu_umnt

