#!/bin/bash

#Transfer my /Home song files into QEMU.

~/TOS/Bin/QEMU/emu_mnt
rm -R /mnt/qemu_disk/Home/Sup1/Sup1Hymns
rm -R /mnt/qemu_disk/Home/Sup1/Sup1Songs
cp -R --preserve=timestamps ~/TOS/Home/Sup1/Sup1Hymns /mnt/qemu_disk/Home/Sup1
~/TOS/Bin/QEMU/emu_umnt

