#!/bin/bash

#Transfer my /Home song files out of QEMU.

~/TOS/Bin/QEMU/emu_mnt
rm -R ~/TOS/Home/Sup1/Sup1Hymns
rm -R ~/TOS/Home/Sup1/Sup1Songs
cp -R --preserve=all /mnt/qemu_disk/Home/Sup1/Sup1Hymns ~/TOS/Home/Sup1
chmod -R 777 ~/TOS
~/TOS/Bin/QEMU/emu_umnt

