+] Adam
  +] SysMsgFlags
      sys_msg_flags[0]=0xFF;
      +] SysRegVer
      registry_version=3.110;
      +] TempleOS
  +] CircleTrace
      F64 best_score=4.9425;
      +] TOS
      I64 tos_code_walk_thru=105,tos_after_egypt_in_action=46;
      +] DiningStars
      F64 best_score=9999.0000;
      +] DunGen
      F64 best_score=20.5295;
      +] KeepAway
      I64 best_score0=0,best_score1=9999;
      +] RawHide
      F64 best_score=97.0710;
      +] FlapBat
      F64 best_score=16.4090;
      +] CastleFrankenstein
      F64 best_score=33.8405;
      +] XCaliber
      I64 best_score=248;
    I64 msg_flags=1;
      +] Varoom
      F64 best_score=46.2643;
      +] ZoneOut
      F64 best_score=50.3318;
      +] BlackDiamond
      I64 best_score=9;
      +] Wenceslas
      F64 best_score=49.8074;
      +] EagleDive
      I64 best_score=4;
      +] BomberGolf
      I64 best_score=175;
      +] TimeOut
      I64 best_score=22202;
      +] DemoCompany
  +] Game1
      F64 best_score=166.34088;
    +] SimpleVal
          1262;
            