+] Adam
  +] SysMsgFlags
      sys_msg_flags[0]=0xFF;
      +] SysRegVer
      registry_version=3.060;
      -] TempleOS
  +] CircleTrace
      F64 best_score=4.9425;
      +] TOS
      I64 tos_code_walk_thru=105,tos_after_egypt_in_action=46;
      +] DiningStars
      F64 best_score=9999.0000;
      +] BlackDiamond
      I64 best_score=1;
      +] DunGen
      F64 best_score=20.5295;
      +] ZoneOut
      F64 best_score=50.3318;
      +] Varoom
      F64 best_score=11.8623;
      +] BugBird
      F64 best_score=18.2332;
      +] TimeOut
      I64 best_score=21532;
      +] RawHide
      F64 best_score=81.1088;
      +] KeepAway
      I64 best_score0=0,best_score1=9999;
      +] XCaliber
      I64 best_score=248;
    I64 msg_flags=1;
      +] Wenceslas
      F64 best_score=49.8074;
      +] BomberGolf
      I64 best_score=32;
      +] EagleDive
      I64 best_score=4;
      +] CastleFrankenstein
      F64 best_score=33.8405;
      +] DemoCompany
  +] Game1
      F64 best_score=167.58340;
    +] SimpleVal
          1245;
            